// tslint:disable
export const EnvKeys = [
  'JWTPLAYERKEY',
  'JWTSPECTATEKEY',
  'LOADBALANCERARN',
  'TARGETNAMETEMPLATE',
  'DATABASE_URL',
  'AWSREGION',
];
export type EnvKeysTypes =
  | 'JWTPLAYERKEY'
  | 'JWTSPECTATEKEY'
  | 'LOADBALANCERARN'
  | 'TARGETNAMETEMPLATE'
  | 'DATABASE_URL'
  | 'AWSREGION';
