// tslint:disable
export const EnvKeys=["JWTPLAYERKEY","JWTSPECTATEKEY","LOADBALANCERARN","TARGETNAMETEMPLATE","DATABASE_URL"];
export type EnvKeysTypes="JWTPLAYERKEY"|"JWTSPECTATEKEY"|"LOADBALANCERARN"|"TARGETNAMETEMPLATE"|"DATABASE_URL"