/* This file was generated by https://github.com/schema-driven-rest/plugin-serverless-api-base */
/* tslint:disable */

import {UserController} from './api/UserController';

import {handlerWrapper} from './apiUtils/handlerWrapper';

const UserControllerInstance = new UserController();
export const User_doThing = handlerWrapper(UserControllerInstance.doThing.bind(UserControllerInstance));
